spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?serverTimezone=Asia/Shanghai
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
# 手动创建activiti或者可以使用脚本
  activiti:
    db-history-used: true
    history-level: full
    database-schema-update: true
  security:
    user:
      name: user
      password: password